### ISSUE TITLE
Hello, could you tell me how your code works?

### ISSUE THREAD

**Issue by WANGxue708** [IMES-Lab/edge_learning_ar#1]
Hello, I've been studying convolutional neural networks and edge computing recently. I'm interested in seeing your code, but I don't know how to run it. Can you give me an explanation?

**Comment by devFallingstar** [comment]
@HaOnly  @Ji-Hu and @NaMinsu  are main programmers of this project

Please add some explanation for @WANGxue708 

Thanks.

**Comment by devFallingstar** [comment]
@WANGxue708 Sorry for late reply. 
Since this project is incomplete project, I'm afraid we can't give you any helps.

Thank you for your attention, and if there's any more questions, do not hesitate to contact me.

**Comment by Ji-Hu** [comment]
This project is for CNN model learning on edge - client environment.
server and client code is test code for testing CNN weights and outputs transmission
CNN model are using tensorflow and keras
